version: 2
jobs:
 test:
   working_directory: ~/brandmemo
   docker:
     - image: circleci/node:10-browsers
   steps:
     - checkout
     - run:
         name: node_modulesのインストール
         command: |
           npm install
     - run:
         name: 強制fix
         command: |
           npm run lint
 build-deploy:
   working_directory: ~/brandmemo
   docker:
     - image: circleci/node:10-browsers
   steps:
     - checkout
     - persist_to_workspace:
         root: .
         paths:
          - .
     - run:
         name: package.jsonを読み込む
         command: |
           npm install
     - run:
         name: ビルド
         command: |
           npm run build
     - attach_workspace:
         at: .
     - run:
         name: firebase-toolsのインストール
         command: |
           npm install --dev firebase-tools
     - run:
         name: distの位置を確認
         command: |
           ls -la dist
     - run:
         name: firebaseへデプロイ
         command: |
           ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
 version: 2
 build-test-deploy:
   jobs:
     - test
     - build-deploy:
        requires:
          - test
        filters:
          branches:
            only:
             - master
